### PR TITLE
feat: allow the iframe that allows the images created by bing image creator to be shown

### PR DESCRIPTION
**Pull request by timefox**
1. Allow the iframe that the images created by Bing Image Creator to be shown.
2. Automatically adjust the height of the input box according to user input, the maximum height is half of the current window height.

### CODE REVIEW

**Comment by waylaidwanderer** [comment]
Got any screenshots?

**Comment by timefox** [comment]
> Got any screenshots?

For 1, I have created a pull request to node-chatgpt-api also.
Pls check https://github.com/timefox/node-bic-sydney for a screenshot.

**Comment by timefox** [comment]
Or see here.
chatgptapi_with_pandoraai

**Comment by waylaidwanderer** [comment]
Thanks for the PR!

I see what you're trying to do with the textbox, but I don't think that's the best solution. I have a different solution in mind which should work. If you can remove that from the PR, I'll merge the other change with the iFrame.

In the future, I would recommend you limit PRs to one feature each so that issues with one feature don't block the entire PR from being merged in.

**Comment by timefox** [comment]
Thanks for your suggestion，I have reverted the changes for the textbox.

**Pull request merged**
